### PR TITLE
GPU support

### PR DESCRIPTION
**Pull request by Ok3ks**
Added couple lines of code to move the model to a gpu device if present on device. Mps supports M1 chips, while coda supports Nvidia chips. Else use CPU

### CODE REVIEW

**Comment by chidiwilliams** [comment]
Thanks a lot. Did you test that it works fine with your GPU?

**Comment by Ok3ks** [comment]
I will, I just have issues sorting out the environment as I use an
earlier version of python

**Comment by Ok3ks** [comment]
Still have issues with the environment, but you can test the lines of code in your own environment if it works

**Comment by matthiashaldimann** [comment]
I would be happy to help with testing GPU inference on windows, but can't build or run buzz from source on windows.
(Running the executable version works.)

- I found that poetry does not install the modules sounddevice, whisper, stable-ts and pyaudio. After adding these, no more import errors.
- However, I still get "TypeError: unsupported operand type(s) for |: ..." errors at various locations in the code before the GUI loads.

I there anything particular that must be observed but is not mentioned in readme.md to be able to run / build on windows?

**Comment by ain-soph** [comment]
This certainly shall work, but I advise to add a `force_cpu` option to allow using CPU even if GPU exists.

**Comment by ain-soph** [comment]
@chidiwilliams Tested on Windows with RTX2080 and everything works fine. 

CUDA driver version: 12.0

```
python=3.10
pytorch=1.13.1
pytorch-cuda=11.7
```

Note: we may need an exception catch for `out_of_memory` issue (to suggest users to smaller models / free their GPU memory / use CPU instead):

```
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\ain-s\miniconda3\envs\buzz\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\ain-s\miniconda3\envs\buzz\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\workspace\buzz\buzz\transcriber.py", line 436, in transcribe_whisper
    model = whisper.load_model(task.model_path)
  File "C:\Users\ain-s\miniconda3\envs\buzz\lib\site-packages\whisper\__init__.py", line 122, in load_model
    return model.to(device)
  File "C:\Users\ain-s\miniconda3\envs\buzz\lib\site-packages\torch\nn\modules\module.py", line 989, in to
    return self._apply(convert)
  File "C:\Users\ain-s\miniconda3\envs\buzz\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\ain-s\miniconda3\envs\buzz\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\ain-s\miniconda3\envs\buzz\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "C:\Users\ain-s\miniconda3\envs\buzz\lib\site-packages\torch\nn\modules\module.py", line 664, in _apply
    param_applied = fn(param)
  File "C:\Users\ain-s\miniconda3\envs\buzz\lib\site-packages\torch\nn\modules\module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 8.00 GiB total capacity; 6.93 GiB already allocated; 0 bytes free; 7.27 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Exception ignored in atexit callback: <function shutdown at 0x0000027435330A60>
```

**Comment by ain-soph** [comment]
But I just realize current codes only change `device` in `RecordingTranscriber`.

What about `WhisperCppFileTranscriber`, `WhisperFileTranscriber`, `transcribe_whisper`?

Besides, `whisper.load_model` api already has a `device` argument. It's better to use that instead of changing device by ourselves.

**Pull request closed without merging**
