### PR TITLE
Cn language support

### PR DESCRIPTION
**Pull request by Chenghao999**

### CODE REVIEW

**Comment by Chenghao999** [comment]
i am not good at use GitHub. I may have brought a lot to everyone, and I apologize for disturbing yo

**Comment by raivisdejus** [comment]
@Chenghao999 Thanks for your contribution. I welcome new translations and improvements.

**Comment by Chenghao999** [comment]
i also interested in translate our documentation page

**Comment by raivisdejus** [comment]
@Chenghao999 Good idea. I have created issue https://github.com/chidiwilliams/buzz/issues/987
Will prepare support for documentation page localization and then you can translate.

**Pull request merged**
